version: '3.1'
services:
  db:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=techtest_db
    ports:
      - 5454:5432
    # Create a volume to persist data
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: