version: '3.1'
services:
  db:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5454:5432
    # Create a volume to persist data
    volumes:
      - pg_data:/var/lib/postgresql/data
  api:
    build: .    
    container_name: techtest_api
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "${PORT}:${PORT}"
      - "5555:5555"
    volumes:
      - .:/app
    command: npm run start
volumes:
  pg_data: